package:
  version: 1.4.6
  url: https://github.com/pooza/ginseng-fediverse
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng Fediverse libraries
  license: MIT
test:
  filters:
    - name: ci
      cases:
        - mastodon_service_test
        - misskey_service_test
        - meisskey_service_test
        - pleroma_service_test
hashtag:
  pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
acct:
  pattern: '((?<=^|[^\/[:word:]])@(([a-z0-9_]+([a-z0-9_\.-]+[a-z0-9_]+)?)(?:@[a-z0-9\.\-]+[a-z0-9]+)?))'
parser:
  toot:
    visibility:
      unlisted: unlisted
      private: private
      direct: direct
    url:
      patterns:
        - ^/web/statuses/([[:digit:]]+)
        - ^/@[[:word:]]+/([[:digit:]]+)
        - ^/users/[[:word:]]+/statuses/([[:digit:]]+)
        - ^/notice/([[:word:]]+)
  note:
    visibility:
      unlisted: home
      private: followers
      direct: specified
    url:
      patterns:
        - ^/notes/([[:alnum:]]+)
mastodon:
  url: https://st.mstdn.b-shock.org/
  token: test
  test_toot: 1
  toot:
    max_length: 500
  followers:
    limit: 500
  followees:
    limit: 500
misskey:
  url: https://dev.mis.b-shock.org/
  token: test
  note:
    max_length: 500
pleroma:
  url: https://dev.ple.b-shock.org/
  token: test
meisskey:
  url: https://dev.mei.b-shock.org/
  token: test
