package:
  version: 1.0.2
  url: https://github.com/pooza/ginseng-fediverse
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng Fediverse libraries
  license: MIT
hashtag:
  pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
mastodon:
  url: https://st.mstdn.b-shock.org/
  token: test
  test_toot: 1
  followers:
    limit: 500
  followees:
    limit: 500
misskey:
  url: https://dev.mis.b-shock.org/
  token: test
dolphin:
  url: https://dev.dol.b-shock.org/
  token: test
