acct:
  pattern: ((?<=^|[^\/[:word:]])@(([a-z0-9_]+([a-z0-9_\.-]+[a-z0-9_]+)?)(?:@[a-z0-9\.\-]+[a-z0-9]+)?))
hashtag:
  pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
mastodon:
  followees:
    limit: 500
  followers:
    limit: 500
  status:
    default_max_length: 500
  test_toot: 1
  token: test
  url: https://st.mstdn.b-shock.org/
meisskey:
  attachment:
    limit: 8
  status:
    default_max_length: 1000
  token: test
  url: https://st.reco.shrieker.net/
misskey:
  attachment:
    limit: 16
  status:
    default_max_length: 3000
  token: test
  url: https://st.misskey.delmulin.com/
mulukhiya:
  url: https://st.mstdn.b-shock.org/
package:
  authors:
    - Tatsuya Koishi
  description: ginseng Fediverse libraries
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/ginseng-fediverse
  version: 1.8.9
parser:
  note:
    url:
      patterns:
        - ^/notes/([[:alnum:]]+)
    visibility:
      direct:
        icon: envelope
        name: specified
      private:
        icon: lock
        name: followers
      public:
        icon: globe
        name: public
      unlisted:
        icon: house
        name: home
  toot:
    url:
      patterns:
        - ^/web/statuses/([[:digit:]]+)
        - ^/@[[:word:]]+/([[:digit:]]+)
        - ^/users/[[:word:]]+/statuses/([[:digit:]]+)
        - ^/notice/([[:word:]]+)
    visibility:
      direct:
        icon: envelope
        name: direct
      private:
        icon: lock
        name: private
      public:
        icon: earth-asia
        name: public
      unlisted:
        icon: lock-open
        name: unlisted
pleroma:
  attachment:
    limit: 4
  status:
    default_max_length: 5000
  token: test
  url: https://leroma.shrieker.net/
