package:
  version: 1.7.14
  url: https://github.com/pooza/ginseng-fediverse
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng Fediverse libraries
  license: MIT
hashtag:
  pattern: (?:^|[^\/\)\w])#([[:word:]_]*[[:alpha:]_·][[:word:]_]*)
acct:
  pattern: '((?<=^|[^\/[:word:]])@(([a-z0-9_]+([a-z0-9_\.-]+[a-z0-9_]+)?)(?:@[a-z0-9\.\-]+[a-z0-9]+)?))'
parser:
  toot:
    visibility:
      unlisted:
        name: unlisted
      private:
        name: private
      direct:
        name: direct
    url:
      patterns:
        - ^/web/statuses/([[:digit:]]+)
        - ^/@[[:word:]]+/([[:digit:]]+)
        - ^/users/[[:word:]]+/statuses/([[:digit:]]+)
        - ^/notice/([[:word:]]+)
  note:
    visibility:
      unlisted:
        name: home
      private:
        name: followers
      direct:
        name: specified
    url:
      patterns:
        - ^/notes/([[:alnum:]]+)
mastodon:
  url: https://st.mstdn.b-shock.org/
  token: test
  test_toot: 1
  toot:
    default_max_length: 500
  followers:
    limit: 500
  followees:
    limit: 500
misskey:
  url: https://dev.mis.b-shock.org/
  token: test
  note:
    default_max_length: 500
  attachment:
    limit: 16
pleroma:
  url: https://leroma.shrieker.net/
  token: test
  toot:
    default_max_length: 5000
  attachment:
    limit: 4
meisskey:
  url: https://st.reco.shrieker.net/
  token: test
  note:
    default_max_length: 500
  attachment:
    limit: 8
mulukhiya:
  url: https://st.mstdn.b-shock.org/
